name:                expand-path
version:             0.1.0.0
github:              "npj/expand-path"
license:             BSD3
author:              "Peter Brindisi"
maintainer:          "peter.brindisi@gmail.com"
copyright:           "2018 Peter Brindisi"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/expand-path#readme>

dependencies:
- base >= 4.7 && < 5
- directory
- unix
- filepath

library:
  source-dirs: src

tests:
  expand-path-test:
    main:                Tasty.hs
    source-dirs:         test
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - expand-path
    - tasty
    - tasty-discover
    - tasty-hspec
    - hspec
